### ISSUE TITLE
(scheduler +59s) Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.

### ISSUE THREAD

**Issue by qyh-stbz** [Shanghai-Digital-Brain-Laboratory/DB-Football#5]
Hello, I tried to run the training code according to the readme file you provided, and the warning as described by Title appeared, and I didn't see the training process, is there any way to solve it？

**Comment by YanSong97** [comment]
This is likely due to the resource shortage raised by Ray.  As we run each rollout worker on each single CPU core by default, we recommend double-checking the number of rollout worker and try reducing it.

**Comment by YanSong97** [comment]
If there is no further question. I will close this issue for now.
