### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'

### ISSUE THREAD

**Issue by ktimam** [Shanghai-Digital-Brain-Laboratory/DB-Football#7]
Trying to run:
python3 -m gfootball.examples.run_ppo2 --level=10_vs_10_kaggle

Gives the following error:
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'

My understanding this is due to not using Tensorflow 1.15.* as instructed in GRF, but Tensorflow 1.15.* isn't available for python versions above 3.6, which contradicts with instructions to use python3.9! 

What versions should be used for Python and Tensorflow to be able to run scenarios!?

**Comment by YanSong97** [comment]
Hi, this is likely due to the tf support of openai/baselines and I suggest having a look at their docs.

We mainly used torch instead and ran our codebase on py3.8 & 3.9.

**Comment by ktimam** [comment]
Seems issue was caused because of openai/baselines indeed. Without its working fine. 
Thanks a lot for help.
